### ISSUE TITLE
homework review completed, 請調整

### ISSUE THREAD

**Issue by hatelove** [Oliver721003/TDD-Homework#1]
建議如下：

1. 第一個測試案例有誤：
`        public void ComputeByGroupTest_group_3_sum_Case()`
`            string property = "Case";`
這不只是手誤，而是在寫測試案例的時候，把心思放太多在寫程式，而不是放在需求和 domain 上。因為在 domain 上，會很清楚現在要 sum 的是成本 (Cost)

1. orders 的初始化建議不要用 .Add(), 參考下面的作法，語意會更清楚，而且寫起來更快。
```
			var products = new List<Product>()
			{
				new Product() { Id=1 ,Cost=1 ,Revenue=11,SellPrice=21 },
				new Product() { Id=2 ,Cost=2 ,Revenue=12,SellPrice=22 },
				new Product() { Id=3 ,Cost=3 ,Revenue=13,SellPrice=23 },
				new Product() { Id=4 ,Cost=4 ,Revenue=14,SellPrice=24 },
				new Product() { Id=5 ,Cost=5 ,Revenue=15,SellPrice=25 },
				new Product() { Id=6 ,Cost=6 ,Revenue=16,SellPrice=26 },
				new Product() { Id=7 ,Cost=7 ,Revenue=17,SellPrice=27 },
				new Product() { Id=8 ,Cost=8 ,Revenue=18,SellPrice=28 },
				new Product() { Id=9 ,Cost=9 ,Revenue=19,SellPrice=29 },
				new Product() { Id=10,Cost=10,Revenue=20,SellPrice=30 },
				new Product() { Id=11,Cost=11,Revenue=21,SellPrice=31 }
			};
```

1. OrderCollection 這個 class 的命名不是很好，一來是跟需求的語意不搭，二來是 Collection 後綴詞在 C# 往往是定義一個集合資料結構的類別。如果你想要針對集合去設計這個API，建議你使用 extension method 針對某些集合型別作擴充。

**Comment by Oliver721003** [comment]
已針對命名與設計進行修正

**Comment by Oliver721003** [comment]
ver 3 => 使用 擴充方法 針對 List<Order> 做擴充

p.s 須在針對Linq中的Func< >等語法進行了解與應用

**Comment by hatelove** [comment]
就是這樣，這樣的 API 是否看起來語意比原本的清楚很多，而且使用端更簡單用了呢？

**Comment by hatelove** [comment]
我也提供我的 sample solution 供您參考一下，http://bit.ly/91-tdd-day1-homework-solution
第一版只有支援 Product, 第二版則透過 extension method + generic + lambda 來支援任意型別，這樣 API 語意清楚，呼叫端使用方便。也建議您可以參考一下 production code 的作法。
